# Generated by Django 6.0 on 2026-01-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('1', 'Administrator'), ('2', 'Users'), ('3', 'Support'), ('4', 'Teacher')], default='2', max_length=25),
        ),
    ]
